// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/subtasks/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subtasks/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subtasks/[id].patch').default>>>>
    }
    '/api/subtasks': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subtasks/index.post').default>>>>
    }
    '/api/tasks/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].put').default>>>>
    }
    '/api/tasks/:id/subtasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id]/subtasks.get').default>>>>
    }
    '/api/tasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_openapi.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nitropack/dist/runtime/internal/routes/openapi').default>>>>
    }
    '/_scalar': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nitropack/dist/runtime/internal/routes/scalar').default>>>>
    }
    '/_swagger': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nitropack/dist/runtime/internal/routes/swagger').default>>>>
    }
  }
}
export {}